services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - '8000:8000'
    volumes:
      - ./api:/api
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    depends_on:
      - postgres
    stdin_open: true
    tty: true

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./client:/client
    stdin_open: true
    tty: true

  postgres:
    image: postgres:latest
    networks:
      - backend
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
